# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Testing Grounds
email: b.c.gilmour@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  What could potentially be a future static profile, but is currently a thing I get to fool around with.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcgilmour.github.io" # the base hostname & protocol for your site
twitter_username: [N/A]
github_username:  bcgilmour

# Build settings
markdown: kramdown
